services:
  - type: web
    name: tubeskds2-inference
    env: docker
    rootDir: TubesKDS2
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: LOAD_DATA
        value: "0"
      - key: LOAD_ODE_HMM
        value: "1"
      - key: WEB_CONCURRENCY
        value: "1"
    healthCheckPath: /api/status
